name: Pacman CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update pacman and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git

      - name: Run your script or tests
        run: |
          echo "Running build or test commands"
          # e.g., make, python script.py, etc.
